### ISSUE TITLE
Add mouse support to 4.6 version

### ISSUE THREAD

**Issue by Chrysostomus** [oberon2007/dmenu-manjaro#1]
I found a new patch on suckless site:
http://tools.suckless.org/dmenu/patches/mouse-support-msel
This should work on 4.6, but I have not tested how it interacts with our other patches.

**Comment by oberon2007** [comment]
Cool. I will figure it out later :)
Thanks a lot!

**Comment by oberon2007** [comment]
Lets check the new pkg a bit before pushing it:
```
sudo pacman -U http://www.oberon.at/oberon/src/dmenu-manjaro-4.6-1-x86_64.pkg.tar.xz
```

**Comment by Chrysostomus** [comment]
Mouse support and multiselect seem to work. I imagined that the new requirements for font arguments would cause my scripts to fail, but instead dmenu just falls back to using default font. This is very good. However, the new height patch wants -lh instead of -h to pass heigth arguments. I think we should edit the patch to use -h, so no functionality breaks for users of current version.

**Comment by oberon2007** [comment]
Sure we could do that. Are you sure it is better than adjusting the bspwm config and add an install message about the change in **dmenu-manjaro**? One can assume that the original patcher will stick to the new way, so very likely we'll have to patch the patch also for all future releases... ;)

**Comment by Chrysostomus** [comment]
I made the change already. It is very simple modification that takes 2 minutes and less if you use find&replace function. Bspwm does not use this function actually. I wanted to add it incase somebody wants to resurrect the awesome respin. But anyway, if somwbody is using the old way, syntax change will just cause their dmenu keybindings to just fail, which can be difficult to fix on minimalist system with little experience. 

If dmenu would have -h option for help, the new syntax would make sense. But since it does not, -h flag is more consostent with widht option (-w). So I'd still favor the change.

**Comment by oberon2007** [comment]
ok, thanks! I'll build it like that then.
btw, is multiselect a new feature for dmenu-manjaro or did I simply miss it until now? ;)

**Comment by Chrysostomus** [comment]
For dmenu-manjaro it is new. It has been available as patch, and now got nerged into mainline.
