### ISSUE TITLE
When accidentaly type"[" in dmenu, recent list gets wiped out

### ISSUE THREAD

**Issue by freed00m** [oberon2007/dmenu-manjaro#2]
It's simple and it was happening since i3 Manjaro 8.13,

What I did

typed 'hto[' instead of 'htop' and whole list in ~/.cache/dmenu-recent/recent gets wiped out, it is reproducable every time.

---

And I am bit confused about what it suppose to be in ~/.cache/dmenu-recent/all cause that file is always empty, the full list of command are at ~/.cache/dmenu_run there is some funky stuff going on, 

the terminal/background lists are at ~/.config/dmenu-recent/

It's confusing in my opinion but that's not the issue, the issue is these "[" "]"

**Comment by oberon2007** [comment]
@Chrysostomus , can you have a look, please!

**Comment by Chrysostomus** [comment]
My first guedd would be that it has something to do with "["  being a shell command for "test". No idea why "]" would cause this though. I'll lool into it when I have time.

**Comment by oberon2007** [comment]
@freed00m @Chrysostomus I am deleting this repo. Let's now only use the [manjaro community repo](https://github.com/manjaro/packages-community/tree/master/dmenu-manjaro)
